version: '3.9'

services:
  cwebp_docker_api:
    image: ghcr.io/aspnmy/cwebp_docker_api:latest
    container_name: cwebp_docker_api
    environment:
      - DELTIME=0
      - IMGSIZE=100
      - X_API_KEY=${X_API_KEY}
    volumes:
      - ${img_webp_path}:/app/img_webp
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
