version: '3.9'

services:
  cwebp-api:
    build:
      context: .
      dockerfile: Containerfile
    image: localhost/cwebp-api:latest
    container_name: cwebp-api
    ports:
      - "3333:3333"
    environment:
      - DELTIME=72
      - IMGSIZE=100
      - X_API_KEY=dev
    volumes:
      - ./img_webp:/app/img_webp
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3333/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - label=disable
    user: 1000:1000
